### ISSUE TITLE
push dev to main and add readme file

### ISSUE THREAD

**Issue by Remdox** [lucadomene/CircoloCulturale#1]
Hi,

I'm developing a website in JSP for a university project, and your work has been a significant source of inspiration. The quality of your coding far exceeds what Copilot could achieve.

However, I noticed that the recent changes in the dev branch have not been pushed to the main branch, even though everything seems to be working fine. Additionally, it would be very helpful for novice users if you could add a README file with a walkthrough on how to run the project.

Thank you!

**Comment by lucadomene** [comment]
Hello, I'm glad someone stumbled upon our little Uni project.

I've done what you requested, cleaned up unneccesary branches and merged everything into main.

I've also added a brief readme file to better guide users into running our application.
As I've already stated in the readme, beware that this project has way too much tech-debt and is not optimized nor refactored at all. 
Many methods could've been engineered better, but we didn't have a lot of time so we decided for the best to just leave it as it was.

We tested this project on IntelliJ installed on Linux Fedora and Windows 11 and it worked "fine". The only browsers we tested it on were Firefox and Edge, we encountered some quirks with style and formatting but we haven't fixed it.

Please let me know wether I can do anything else to further assist you.

Kindest regards, Luca (and Sara, my project mate).

**Comment by Remdox** [comment]
Thanks!
